# Generated by Django 5.1.1 on 2024-11-09 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_video_author_alter_video_thumbnail_alter_video_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Vídeo'),
        ),
        migrations.CreateModel(
            name='VideoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(max_length=255, verbose_name='Videos')),
                ('status', models.CharField(choices=[('UPLOADED_STARTED', 'Upload iniciado'), ('PROCESSING_STARTED', 'Processamento Iniciado'), ('PROCESSING_FINISHED', 'Processamento finalizado'), ('PROCESSING_ERROR', 'Erro no Processamento')], default='UPLOADED_STARTED', max_length=20, verbose_name='Status')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_media', to='core.video', verbose_name='Vídeo')),
            ],
        ),
    ]
