# Generated by Django 5.1.1 on 2024-11-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_video_video_alter_videomedia_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
